export {
  ASPECT_RATIO_OPTIONS,
  THUMBNAIL_LAYOUT_HEIGHT_MAX as HEIGHT_MAX,
  THUMBNAIL_LAYOUT_HEIGHT_MIN as HEIGHT_MIN,
  THUMBNAIL_LAYOUT_WIDTH_MAX as WIDTH_MAX,
  THUMBNAIL_LAYOUT_WIDTH_MIN as WIDTH_MIN,
} from "$lib/grid-layout/thumbnail-layout-bounds";

export const POSITION_MIN = -10000;
export const POSITION_MAX = 31000;
export const OPACITY_MIN = 0.1;
export const OPACITY_MAX = 1;
export const BORDER_THICKNESS_MIN = 0;
export const BORDER_THICKNESS_MAX = 12;
export const DECLOAK_FLASH_THICKNESS_MIN = 1;
export const DECLOAK_FLASH_THICKNESS_MAX = 12;
export const DECLOAK_FLASH_DURATION_MIN = 250;
export const DECLOAK_FLASH_DURATION_MAX = 10000;
