CREATE TABLE IF NOT EXISTS Profile (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL UNIQUE,
  DeletedAt TEXT NULL,
  IsActive INTEGER NOT NULL DEFAULT 0,
  SwitchHotkey TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ProcessesToPreview (
  ProfileId INTEGER NOT NULL,
  ProcessName TEXT NOT NULL,
  PRIMARY KEY (ProfileId, ProcessName),
  FOREIGN KEY (ProfileId) REFERENCES Profile(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ThumbnailDefaultConfig (
  ProfileId INTEGER NOT NULL PRIMARY KEY,
  Width INTEGER NOT NULL DEFAULT 400,
  Height INTEGER NOT NULL DEFAULT 300,
  X INTEGER NOT NULL DEFAULT 100,
  Y INTEGER NOT NULL DEFAULT 100,
  Opacity REAL NOT NULL DEFAULT 0.75,
  FocusBorderColor TEXT NOT NULL DEFAULT '#0078D4',
  FocusBorderThickness INTEGER NOT NULL DEFAULT 3,
  ShowTitleOverlay INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (ProfileId) REFERENCES Profile(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ThumbnailSettings (
  ProfileId INTEGER NOT NULL,
  WindowTitle TEXT NOT NULL,
  Width INTEGER NOT NULL,
  Height INTEGER NOT NULL,
  X INTEGER NOT NULL,
  Y INTEGER NOT NULL,
  Opacity REAL NOT NULL,
  FocusBorderColor TEXT NOT NULL DEFAULT '#0078D4',
  FocusBorderThickness INTEGER NOT NULL DEFAULT 3,
  ShowTitleOverlay INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (ProfileId, WindowTitle),
  FOREIGN KEY (ProfileId) REFERENCES Profile(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AppSettings (
  Key TEXT NOT NULL PRIMARY KEY,
  Value TEXT NOT NULL
);
