CREATE TABLE IF NOT EXISTS MumbleServerGroups (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  DisplayOrder INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MumbleLinks (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Url TEXT NOT NULL,
  DisplayOrder INTEGER NOT NULL DEFAULT 0,
  IsSelected INTEGER NOT NULL DEFAULT 0,
  Hotkey TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS MumbleLinkGroups (
  LinkId INTEGER NOT NULL,
  GroupId INTEGER NOT NULL,
  PRIMARY KEY (LinkId, GroupId),
  FOREIGN KEY (LinkId) REFERENCES MumbleLinks(Id) ON DELETE CASCADE,
  FOREIGN KEY (GroupId) REFERENCES MumbleServerGroups(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MumbleLinksOverlaySettings (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AlwaysOnTop INTEGER NOT NULL DEFAULT 1,
  X INTEGER NOT NULL DEFAULT 100,
  Y INTEGER NOT NULL DEFAULT 100,
  Width INTEGER NOT NULL DEFAULT 300,
  Height INTEGER NOT NULL DEFAULT 400
);

CREATE TABLE IF NOT EXISTS ClientGroups (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ProfileId INTEGER NOT NULL,
  Name TEXT NOT NULL,
  DisplayOrder INTEGER NOT NULL DEFAULT 0,
  CycleForwardHotkey TEXT NOT NULL DEFAULT '',
  CycleBackwardHotkey TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (ProfileId) REFERENCES Profile(Id) ON DELETE CASCADE,
  UNIQUE(ProfileId, Name)
);

CREATE TABLE IF NOT EXISTS ClientGroupMembers (
  GroupId INTEGER NOT NULL,
  WindowTitle TEXT NOT NULL,
  DisplayOrder INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (GroupId, WindowTitle),
  FOREIGN KEY (GroupId) REFERENCES ClientGroups(Id) ON DELETE CASCADE
);
